default: tilesconv_8_8

tilesconv_8_8.o: main.c
	gcc -c main.c -o tilesconv_8_8.o

tilesconv_8_8: tilesconv_8_8.o
	gcc tilesconv_8_8.o -o tilesconv_8_8

clean:
	-rm -f tilesconv_8_8.o
	-rm -f tilesconv_8_8
    
