default: bmpconv_24_8

bmpconv_24_8.o: main.c
	gcc -c main.c -o bmpconv_24_8.o

bmpconv_24_8: bmpconv_24_8.o
	gcc bmpconv_24_8.o -o bmpconv_24_8

clean:
	-rm -f bmpconv_24_8.o
	-rm -f bmpconv_24_8
    
